#!/bin/bash

rm -rf test.pdb.d

../../bin/ibp-ng -v -v \
 --input test.fa --seqid 2 \
 --psf test.psf \
 --dmdgp test.dmdgp \
 --output test.dcd \
 --format dcd \
 --restraints test2.res \
 --topology ../../lib/ibp-protein.top \
 --params ../../lib/ibp-protein.par \
 --reorder ../../lib/ibp-protein.ord \
 --threads 1 \
 --method dist,impr,energy \
 --limit 1000 --branch-eps 0.01 --branch-max 128 --vdw-scale 0.5

