#!/bin/bash

kmin=1
kmax=4

if [ "${1}" == "clean" ]; then
  for k in $(seq ${kmin} ${kmax}); do
    for x in psf dcd dmdgp out err dat; do
      rm -f order-${k}.${x}
    done
  done
  exit
fi

for k in $(seq ${kmin} ${kmax}); do
  ../../bin/ibp-ng -v -v \
   --input  orders.fa    \
   --output /dev/null    \
   --psf        order-${k}.psf   \
   --dmdgp      order-${k}.dmdgp \
   --restraints order-${k}.res   \
   --reorder    order-${k}.ord   \
   --topology ../../lib/ibp-protein.top \
   --params   ../../lib/ibp-protein.par \
   --format dcd --threads 1 --method dist,impr \
   --limit 16384 --branch-eps 0.01 --branch-max 64 \
   --rmsd 1.0 --ddf-tol 0.1 --vdw-scale 0.5 \
    1>order-${k}.out 2>order-${k}.err

  awk '/^DEBUG/ {print $2, $3}' order-${k}.out | sort -u > order-${k}.dat
done

