
% r_dihe(): function for writing dihedral restraints.
function r_dihe (num1, res1, num2, res2, num3, res3, num4, res4, d0, dlim)
  printf(['assign ', ...
          '(resid %2d and name %2s) (resid %2d and name %2s)\n', ...
          '       ', ...
          '(resid %2d and name %2s) (resid %2d and name %2s)', ...
          ' 1.0 %8.3f %8.3f 1\n'], ...
          num1, res1, num2, res2, ...
          num3, res3, num4, res4, ...
          d0, dlim);
end

